[package]
name = "linguist-anki"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
linguist-core.workspace = true
linguist-config.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
url.workspace = true
base64.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true
