MODERNIZATION_PROMPT = """
You are an expert language teacher and translator.
I have an image of a flashcard. Please extract the Japanese (or English) text and its meaning.
Return ONLY a strictly valid JSON object with the following schema:
{
    "extracted_text": "The main terminology found in the image",
    "meaning": "The overall meaning or definition",
    "reading": "The phonetic reading (e.g. hiragana/romaji) if applicable",
    "context": "Any contextual clues or example sentences found in the image, or generated by you to help remember it."
}
"""

INGESTION_PROMPT = """
You are an expert language teacher.
Given the following vocabulary word and dictionary definition, generate a high-quality, natural example sentence using this word. Provide a translation for the sentence.
Return ONLY a strictly valid JSON object with the following schema:
{{
    "example_sentence": "Your example sentence here",
    "translation": "Translation of the example sentence"
}}

Vocabulary: {word}
Definition: {definition}
"""
